'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';

type Row=Record<string,any>;
function parse(raw:any){try{return JSON.parse(String(raw||'{}'))}catch{return {text:String(raw||''),thumbnailUrl:''}}}
export default function RulesAdmin(){
 const [authed,setAuthed]=useState(false),[rows,setRows]=useState<Row[]>([]),[msg,setMsg]=useState(''),[loading,setLoading]=useState(false);
 useEffect(()=>{fetch('/api/auth/me').then(r=>r.json()).then(d=>{if(d.ok){setAuthed(true);load()}}).catch(()=>{})},[]);
 async function login(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const password=new FormData(e.currentTarget).get('password');const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});if(r.ok){setAuthed(true);load()}else setMsg('Wrong admin password')}
 async function load(){setLoading(true);const r=await fetch('/api/admin/content_plan');if(r.status===401){setAuthed(false);setLoading(false);return}const d=await r.json();setRows((Array.isArray(d)?d:[]).filter((x:any)=>x.type==='rule'));setLoading(false)}
 async function add(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const notes=JSON.stringify({text:f.get('text')||'',thumbnailUrl:f.get('thumbnail_url')||''});const body={title:f.get('title'),type:'rule',date:f.get('date')||null,status:f.get('status')||'Ready',notes};const r=await fetch('/api/admin/content_plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});setMsg(r.ok?'Rule added':'Add failed');if(r.ok){e.currentTarget.reset();load()}}
 async function del(id:string){if(!confirm('Delete rule?'))return;const r=await fetch('/api/admin/content_plan/'+id,{method:'DELETE'});setMsg(r.ok?'Rule deleted':'Delete failed');if(r.ok)load()}
 if(!authed)return <main className='section'><div className='wrap'><div className='center'><b className='red'>RULE ADMIN</b><h1 className='h2'>Manage Rules</h1></div><form onSubmit={login} className='card form' style={{maxWidth:520,margin:'auto'}}><input className='input' name='password' type='password' placeholder='Admin password' required/><button className='btn red'>Login Admin</button>{msg&&<p className='toast'>{msg}</p>}</form></div></main>;
 return <main className='section'><div className='wrap'><div className='center'><b className='red'>RULE ADMIN</b><h1 className='h2'>Add / Remove Rules</h1><p className='muted'>Thumbnail optional hai. Image URL paste kar sakte ho.</p></div><div className='row' style={{marginBottom:18}}><Link className='btn' href='/rules'>Public Rules</Link><button className='btn' onClick={load}>Refresh</button>{msg&&<b className='toast'>{msg}</b>}</div><form onSubmit={add} className='card form' style={{marginBottom:20}}><h2>Add Rule</h2><div className='grid grid2'><input className='input' name='title' placeholder='Rule title' required/><input className='input' name='status' placeholder='Status e.g. Ready'/><input className='input' name='date' type='date'/><input className='input' name='thumbnail_url' placeholder='Optional thumbnail image URL'/></div><textarea className='input' name='text' placeholder='Rule details'/><button className='btn red'>Add Rule</button></form>{loading&&<p className='muted'>Loading...</p>}<div className='grid grid3'>{rows.map(r=>{const n=parse(r.notes);return <div className='card' key={r.id} style={{padding:0,overflow:'hidden'}}>{n.thumbnailUrl&&<img src={n.thumbnailUrl} alt={r.title} style={{width:'100%',height:170,objectFit:'cover',display:'block'}}/>}<div style={{padding:18}}><h3>{r.title}</h3><p className='muted'>{n.text}</p><button className='btn' onClick={()=>del(r.id)}>Delete</button></div></div>})}</div></div></main>
}