'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';

type Row=Record<string,any>;
export default function RulesAdmin(){
 const [authed,setAuthed]=useState(false),[rows,setRows]=useState<Row[]>([]),[msg,setMsg]=useState(''),[loading,setLoading]=useState(false);
 async function check(){fetch('/api/auth/me').then(r=>r.json()).then(d=>{if(d.ok){setAuthed(true);load()}}).catch(()=>{})}
 useEffect(()=>{check()},[]);
 async function login(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const password=new FormData(e.currentTarget).get('password');const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});if(r.ok){setAuthed(true);load()}else setMsg('Wrong admin password')}
 async function load(){setLoading(true);const r=await fetch('/api/admin-rules');const d=await r.json();setRows(Array.isArray(d)?d:[]);setLoading(false)}
 async function add(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const body={title:f.get('title'),description:f.get('description'),thumbnailUrl:f.get('thumbnailUrl'),status:f.get('status')||'Active'};const r=await fetch('/api/admin-rules',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});setMsg(r.ok?'Saved':'Save failed');if(r.ok){e.currentTarget.reset();load()}}
 async function del(id:string){const r=await fetch('/api/admin-rules/'+id,{method:'DELETE'});setMsg(r.ok?'Removed':'Remove failed');if(r.ok)load()}
 if(!authed)return <main className='section'><div className='wrap'><div className='center'><b className='red'>GUIDELINES ADMIN</b><h1 className='h2'>Manage Guidelines</h1></div><form onSubmit={login} className='card form' style={{maxWidth:520,margin:'auto'}}><input className='input' name='password' type='password' placeholder='Admin password' required/><button className='btn red'>Login Admin</button>{msg&&<p className='toast'>{msg}</p>}<Link className='btn' href='/rules'>Back</Link></form></div></main>;
 return <main className='section'><div className='wrap'><div className='center'><b className='red'>GUIDELINES ADMIN</b><h1 className='h2'>Add / Remove Guidelines</h1><p className='muted'>Thumbnail URL optional hai.</p></div><form onSubmit={add} className='card form' style={{marginBottom:20}}><div className='grid grid2'><input className='input' name='title' placeholder='Title' required/><input className='input' name='status' placeholder='Status'/><input className='input' name='thumbnailUrl' placeholder='Optional thumbnail image URL'/></div><textarea className='input' name='description' placeholder='Description'/><button className='btn red'>Add</button>{msg&&<p className='toast'>{msg}</p>}</form><div className='row' style={{marginBottom:18}}><button className='btn' onClick={load}>Refresh</button><Link className='btn' href='/rules'>Public Page</Link></div>{loading&&<p className='muted'>Loading...</p>}<div className='grid grid3'>{rows.map(r=><div className='card' key={r.id} style={{padding:0,overflow:'hidden'}}>{r.thumbnailUrl&&<img src={r.thumbnailUrl} style={{width:'100%',height:170,objectFit:'cover'}} alt={r.title}/>}<div style={{padding:18}}><h3>{r.title}</h3><p className='muted'>{r.description}</p><span className='tag'>{r.status||'Active'}</span><br/><button className='btn' onClick={()=>del(r.id)}>Remove</button></div></div>)}</div></div></main>
}