'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';

type Row=Record<string,any>;
const OFFICIAL_TAG='【ӢラЯ】';
const fakeNames=['royal drift crew','night racers','blackline mafia','redline crew'];
function isFake(a:Row){return fakeNames.includes(String(a.clan_name||'').toLowerCase().trim()) || String(a.alliance_tag||'').toUpperCase()==='SYN'}
export default function AllianceAdmin(){
 const [authed,setAuthed]=useState(false),[rows,setRows]=useState<Row[]>([]),[msg,setMsg]=useState(''),[loading,setLoading]=useState(false);
 async function check(){fetch('/api/auth/me').then(r=>r.json()).then(d=>{if(d.ok){setAuthed(true);load()}}).catch(()=>{})}
 useEffect(()=>{check()},[]);
 async function login(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setMsg('Checking...');const password=new FormData(e.currentTarget).get('password');const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});if(r.ok){setAuthed(true);setMsg('Admin login done');load()}else setMsg('Wrong admin password')}
 async function load(){setLoading(true);const r=await fetch('/api/admin/alliances');if(r.status===401){setAuthed(false);setLoading(false);return}const d=await r.json();setRows(Array.isArray(d)?d:[]);setLoading(false)}
 async function add(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const body={clan_name:f.get('clan_name'),alliance_tag:OFFICIAL_TAG,leader_instagram:f.get('leader_instagram'),status:f.get('status')||'Active',notes:f.get('notes')};const r=await fetch('/api/admin/alliances',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});setMsg(r.ok?'Alliance added':'Add failed');if(r.ok){e.currentTarget.reset();load()}}
 async function del(id:string){if(!confirm('Remove this alliance?'))return;const r=await fetch('/api/admin/alliances/'+id,{method:'DELETE'});setMsg(r.ok?'Alliance removed':'Remove failed');if(r.ok)load()}
 async function cleanup(){const bad=rows.filter(isFake);if(!bad.length){setMsg('No fake alliance found');return}for(const a of bad){await fetch('/api/admin/alliances/'+a.id,{method:'DELETE'})}setMsg('Fake alliance cards removed');load()}
 const clean=rows.filter(a=>!isFake(a));
 if(!authed)return <main className='section'><div className='wrap'><div className='center'><b className='red'>ALLIANCE ADMIN</b><h1 className='h2'>Manage Official Alliances</h1><p className='muted'>Admin password required.</p></div><form onSubmit={login} className='card form' style={{maxWidth:520,margin:'auto'}}><input className='input' name='password' type='password' placeholder='Admin password' required/><button className='btn red'>Login Admin</button>{msg&&<p className='toast'>{msg}</p>}<Link className='btn' href='/alliance'>Back to Alliance</Link></form></div></main>;
 return <main className='section'><div className='wrap'><div className='center'><b className='red'>ALLIANCE ADMIN</b><h1 className='h2'>Alliance Tag: <span className='red'>{OFFICIAL_TAG}</span></h1><p className='muted'>Yahan se official alliance add/remove karo. Fake SYN cards cleanup kar sakte ho.</p></div><div className='row' style={{marginBottom:18}}><button className='btn red' onClick={cleanup}>Remove Fake Cards</button><button className='btn' onClick={load}>Refresh</button><Link className='btn' href='/alliance'>Public Alliance Page</Link>{msg&&<b className='toast'>{msg}</b>}</div><form onSubmit={add} className='card form' style={{marginBottom:20}}><h2>Add Official Alliance</h2><div className='grid grid2'><input className='input' name='clan_name' placeholder='Clan name' required/><input className='input' name='leader_instagram' placeholder='Leader Instagram'/><input className='input' value={OFFICIAL_TAG} readOnly/><select name='status' defaultValue='Active'><option>Active</option><option>Pending</option><option>Hold</option></select></div><textarea className='input' name='notes' placeholder='Notes'/><button className='btn red'>Add Alliance</button></form>{loading&&<p className='muted'>Loading...</p>}{!clean.length&&<div className='notice muted'>No official alliance added yet.</div>}<div className='grid grid3'>{clean.map(a=><div className='card' key={a.id}><h3>{a.clan_name}</h3><p>Official Tag: <b className='red'>{a.alliance_tag||OFFICIAL_TAG}</b></p><p className='muted'>Leader: {a.leader_instagram||'Not added'} • {a.status||'Active'}</p><p>{a.notes||'Official alliance record.'}</p><button className='btn' onClick={()=>del(a.id)}>Remove</button></div>)}</div></div></main>
}