'use client';
import { useEffect, useState } from 'react';

type Row=Record<string,any>;
function level(notes:string|undefined,key:string){ const m=String(notes||'').match(new RegExp(key+':\\s*([0-9]+)','i')); return m?m[1]:'-'; }
const fallback=[
 ['SOUL Ankit','Head','Core','Active','18','7'],['SOUL Phantom','Co-Leader','Core','Active','15','6'],['SOUL Viper','Captain','Alpha','Active','14','6'],['SOUL Nitro','Driver','Alpha','Trial','12','5'],['SOUL Shadow','Shooter','Bravo','Active','13','5'],['SOUL King','Content Lead','Media','Active','10','4']
].map((m,i)=>({id:String(i),game_name:m[0],role:m[1],team:m[2],activity_status:m[3],notes:`GUN_LEVEL:${m[4]};ARMOR_LEVEL:${m[5]}`,promotion_status:'Eligible',warnings_count:0,alliance_tag:'SYN'}));
export default function Members(){ const [rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true); useEffect(()=>{fetch('/api/public/members').then(r=>r.json()).then(d=>setRows(Array.isArray(d)&&d.length?d:fallback)).catch(()=>setRows(fallback)).finally(()=>setLoading(false))},[]); return <main className="section"><div className="wrap"><div className="center"><b className="red">ROSTER</b><h1 className="h2">SOUL Members</h1><p className="muted">Member role, activity, gun level aur armor level ek saath.</p></div>{loading&&<p className="muted">Loading members...</p>}<div className="grid grid3">{rows.map(m=><div className="card" key={m.id}><div className="split"><h3>{m.game_name}</h3><span className="tag">{m.alliance_tag||'SYN'}</span></div><p className="muted">{m.real_name||'SOUL Member'} • {m.role}</p><p>Team: {m.team} • Status: {m.activity_status}</p><div className="grid grid2" style={{marginTop:14}}><div className="card"><div className="stat">{level(m.notes,'GUN_LEVEL')}</div><p className="muted">Gun Level</p></div><div className="card"><div className="stat">{level(m.notes,'ARMOR_LEVEL')}</div><p className="muted">Armor Level</p></div></div><p className="muted">Promotion: {m.promotion_status} • Warnings: {m.warnings_count||0}</p></div>)}</div></div></main>}
