'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';

type Row=Record<string,any>;
function thumb(desc:any){ const m=String(desc||'').match(/THUMBNAIL_URL:\s*([^;]+);?/i); return m?m[1].trim():''; }
function clean(desc:any){ return String(desc||'').replace(/THUMBNAIL_URL:\s*[^;]+;?/ig,'').trim(); }
function descWithThumb(text:any,url:any){ return `THUMBNAIL_URL:${url||''}; ${text||''}`; }
export default function EventsAdmin(){
 const [authed,setAuthed]=useState(false),[rows,setRows]=useState<Row[]>([]),[msg,setMsg]=useState(''),[loading,setLoading]=useState(false);
 useEffect(()=>{fetch('/api/auth/me').then(r=>r.json()).then(d=>{if(d.ok){setAuthed(true);load()}}).catch(()=>{})},[]);
 async function login(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const password=new FormData(e.currentTarget).get('password');const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});if(r.ok){setAuthed(true);load()}else setMsg('Wrong admin password')}
 async function load(){setLoading(true);const r=await fetch('/api/admin/events');if(r.status===401){setAuthed(false);setLoading(false);return}const d=await r.json();setRows(Array.isArray(d)?d:[]);setLoading(false)}
 async function add(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const body={title:f.get('title'),type:f.get('type'),date:f.get('date'),time:f.get('time'),description:descWithThumb(f.get('description'),f.get('thumbnail_url')),status:f.get('status')||'Planned'};const r=await fetch('/api/admin/events',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});setMsg(r.ok?'Event added':'Add failed');if(r.ok){e.currentTarget.reset();load()}}
 async function del(id:string){if(!confirm('Delete event?'))return;const r=await fetch('/api/admin/events/'+id,{method:'DELETE'});setMsg(r.ok?'Event deleted':'Delete failed');if(r.ok)load()}
 if(!authed)return <main className='section'><div className='wrap'><div className='center'><b className='red'>EVENT ADMIN</b><h1 className='h2'>Manage Events</h1></div><form onSubmit={login} className='card form' style={{maxWidth:520,margin:'auto'}}><input className='input' name='password' type='password' placeholder='Admin password' required/><button className='btn red'>Login Admin</button>{msg&&<p className='toast'>{msg}</p>}</form></div></main>;
 return <main className='section'><div className='wrap'><div className='center'><b className='red'>EVENT ADMIN</b><h1 className='h2'>Add / Remove Events</h1><p className='muted'>Thumbnail optional hai. Image URL paste kar sakte ho.</p></div><div className='row' style={{marginBottom:18}}><Link className='btn' href='/events'>Public Events</Link><button className='btn' onClick={load}>Refresh</button>{msg&&<b className='toast'>{msg}</b>}</div><form onSubmit={add} className='card form' style={{marginBottom:20}}><h2>Add Event</h2><div className='grid grid2'><input className='input' name='title' placeholder='Event title' required/><input className='input' name='type' placeholder='Event type'/><input className='input' name='date' type='date'/><input className='input' name='time' placeholder='Time'/><input className='input' name='status' placeholder='Status e.g. Planned'/><input className='input' name='thumbnail_url' placeholder='Optional thumbnail image URL'/></div><textarea className='input' name='description' placeholder='Description'/><button className='btn red'>Add Event</button></form>{loading&&<p className='muted'>Loading...</p>}<div className='grid grid3'>{rows.map(e=><div className='card' key={e.id} style={{padding:0,overflow:'hidden'}}>{thumb(e.description)&&<img src={thumb(e.description)} alt={e.title} style={{width:'100%',height:170,objectFit:'cover',display:'block'}}/>}<div style={{padding:18}}><h3>{e.title}</h3><p>{e.type} • {e.date} • {e.time}</p><p className='muted'>{clean(e.description)}</p><button className='btn' onClick={()=>del(e.id)}>Delete</button></div></div>)}</div></div></main>
}