'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';

type Row=Record<string,any>;
function info(raw:any){try{return JSON.parse(String(raw||'{}'))}catch{return {description:String(raw||''),thumbnailUrl:''}}}
export default function EventsAdmin(){
 const [authed,setAuthed]=useState(false),[rows,setRows]=useState<Row[]>([]),[msg,setMsg]=useState(''),[loading,setLoading]=useState(false);
 async function check(){fetch('/api/auth/me').then(r=>r.json()).then(d=>{if(d.ok){setAuthed(true);load()}}).catch(()=>{})}
 useEffect(()=>{check()},[]);
 async function login(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const password=new FormData(e.currentTarget).get('password');const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});if(r.ok){setAuthed(true);load()}else setMsg('Wrong admin password')}
 async function load(){setLoading(true);const r=await fetch('/api/admin/events');const d=await r.json();setRows(Array.isArray(d)?d:[]);setLoading(false)}
 async function add(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const description=JSON.stringify({description:f.get('description'),thumbnailUrl:f.get('thumbnailUrl')});const body={title:f.get('title'),type:f.get('type'),date:f.get('date'),time:f.get('time'),status:f.get('status')||'Planned',description};const r=await fetch('/api/admin/events',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});setMsg(r.ok?'Event added':'Add failed');if(r.ok){e.currentTarget.reset();load()}}
 async function del(id:string){if(!confirm('Remove event?'))return;const r=await fetch('/api/admin/events/'+id,{method:'DELETE'});setMsg(r.ok?'Event removed':'Remove failed');if(r.ok)load()}
 if(!authed)return <main className='section'><div className='wrap'><div className='center'><b className='red'>EVENTS ADMIN</b><h1 className='h2'>Manage Events</h1></div><form onSubmit={login} className='card form' style={{maxWidth:520,margin:'auto'}}><input className='input' name='password' type='password' placeholder='Admin password' required/><button className='btn red'>Login Admin</button>{msg&&<p className='toast'>{msg}</p>}<Link className='btn' href='/events'>Back to Events</Link></form></div></main>;
 return <main className='section'><div className='wrap'><div className='center'><b className='red'>EVENTS ADMIN</b><h1 className='h2'>Add / Remove Events</h1><p className='muted'>Thumbnail URL optional hai.</p></div><form onSubmit={add} className='card form' style={{marginBottom:20}}><div className='grid grid2'><input className='input' name='title' placeholder='Event title' required/><input className='input' name='type' placeholder='Event type' required/><input className='input' type='date' name='date'/><input className='input' name='time' placeholder='Time'/><input className='input' name='status' placeholder='Status, e.g. Planned'/><input className='input' name='thumbnailUrl' placeholder='Optional thumbnail image URL'/></div><textarea className='input' name='description' placeholder='Description'/><button className='btn red'>Add Event</button>{msg&&<p className='toast'>{msg}</p>}</form><div className='row' style={{marginBottom:18}}><button className='btn' onClick={load}>Refresh</button><Link className='btn' href='/events'>Public Events Page</Link></div>{loading&&<p className='muted'>Loading...</p>}<div className='grid grid3'>{rows.map(e=>{const d=info(e.description);return <div className='card' key={e.id} style={{padding:0,overflow:'hidden'}}>{d.thumbnailUrl&&<img src={d.thumbnailUrl} style={{width:'100%',height:170,objectFit:'cover'}} alt={e.title}/>}<div style={{padding:18}}><h3>{e.title}</h3><p className='muted'>{e.type} • {e.date||''} • {e.time||''}</p><p>{d.description}</p><button className='btn' onClick={()=>del(e.id)}>Remove</button></div></div>})}</div></div></main>
}